name: Print secrets to logs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
  
      - name: Print to log
        run: |
          echo ${{ secrets.SUPER_SECRET_WORD }} >> $GITHUB_OUTPUT
      
